config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"
  get '/posts/new', to: 'posts#new', as: 'create_post'
  post '/posts/new', to: 'posts#create'
  post '/users/:user_id/posts/:id/', to: 'posts#create_comment'
  post '/users/:user_id/posts/:id/likes', to: 'posts#create_like', as: 'like'
  post '/comments', to: 'comments#new'
  post '/comments/:post_id', to: 'comments#create' 
  post '/likes/:post_id', to: 'likes#create'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_save :update_likes_counter

  def update_likes_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_save :update_comments_counter

  def update_comments_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes
  after_save :update_posts_counter
  validates :title, presence: true
  validates :comments_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def most_recent_comment
    comments.order(created_at: :desc).limit(5)
  end

  def update_posts_counter
    author.update(posts_counter: author.posts.all.length)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def most_recent_post
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.post = Post.find(params[:post_id])
    @comment.author_id = current_user.id
    redirect_to user_post_path if @comment.save
  end

  def new
    @comment = Comment.new
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new(author_id: current_user.id, post: Post.find(params[:post_id]))
    redirect_to user_post_path if @like.save
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    @post.likes_counter = 0
    @post.comments_counter = 0
    return unless @post.save

    redirect_to posts_new_path
  end

  def new
    @post = Post.new
  end

  def create_comment
    @comment = Comment.new(comment_params)
    @comment.post = Post.find(params[:id])
    @comment.author_id = current_user.id
    redirect_to user_post_path if @comment.save
  end

  def create_like
    @like = Like.new(author_id: current_user.id, post: Post.find(params[:id]))
    redirect_to user_post_path if @like.save
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="post">
  <div class="post-title">
      <h3><%= post.title %></h3>
      <div><%= post.text %></div>
    </div>
    <div class="post-props">
      <div>Comments: <%= post.comments_counter%></div>
      <div>Likes: <%= post.likes_counter %></div>
  </div>
</div>

app/views/posts/_user_post.html.erb
<div class="main-div">
  <div class="post-info">
      <h3><%= post.title %> by <%=post.author_id%></h3>
        <div>
          <div>Comments: <%= post.comments_counter%></div>
          <div>Likes: <%= post.likes_counter%></div>
        </div>
  </div>
  <div><%= post.text %><div>
  <%= form_with model: @like, url: like_path, method: :post do |f|%>
    <%= f.submit "Like" %>
  <%end%>
</div>

app/views/posts/index.html.erb
<section>
<% content_for :title, "#{@user.name}'s Posts" %>
<%= render "users/user", user: @user %>
<%@user.posts.each do |post| %>
  <%= link_to user_path(@user, post) do %>
      <%= render "post", post:post %>
        <div> 
          <h3>
            <span>Comments</span>
            <span>for Post: </span>
            <span><%="#{post.title}"%> </span>
          </h3>
          <div class="post-comment">
              <%post.most_recent_comment.each do |comment|%>
                <div>
                  <p>
                      <span><strong><%= comment.author_id %></strong></span>
                      <span><%= comment.text %></span>
                  </p>
                </div>
              <%end%>
          </div>
        </div>
      <%end%>
<%end%>
</section>

app/views/posts/new.html.erb
<div class="post-container">
  <h1>Create New Post</h1>

  <%= form_with model: @post, url: posts_new_path, method: :post, scope: :post do |f| %>
    <div class="inputs">
    <%= f.text_field :Title, placeholder: 'Post Title' %>
    <%= f.text_area :Text, placeholder: 'Details' %>
    <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<%= render "user_post", post: @post %>
<div>
  <%@post.comments.each do |comment|%>
      <div>
          <p>
              <span><strong><% comment.author_id %>:</strong></span>
              <span><% comment.text %></span>
          </p>
      </div>
  <%end%>
</div>

<%= form_with model: @comment, url: user_post_path, method: :post, scope: :comment do |f| %>
  <div>
    <%= f.text_area :text, placeholder: "Add Comment" %>
    <%= f.submit "Comment" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<%=link_to  user_path(user) do %>
  <div class="user-card">
    <div class="user-img">
      <%= image_tag user.photo, alt:"#{user.name}-avatar", class: 'profile-image'%>
    </div>
    <div class="user-props"></div>
      <h3><%= user.name %></h3>
      <div>Number of Posts:<%= user.posts_counter %></div>
    </div>
  </div>
<%end%>

app/views/users/index.html.erb
<%content_for :title, "Blog App"%>
<section class="user-info">
  <%@users.each do |user|%>
    <%=render  "user", user: user %>
  <%end%>
</section>

app/views/users/show.html.erb
<section class="user-section">
  <%= render "user", user: @user%>
  <div class="user-info-show">
    <div class="user-bio">
        <h3>Bio</h3>
        <div class="bio"><%= @user.bio %></div>
    </div>
        <br>
    <div class="user-post">
      <%@user.most_recent_post.each do |post|%>
        <%= link_to user_post_path(@user, post) do %>
          <%= render "posts/post", post: post%>
        <%end%>
      <%end%>
  </div>
  </div>
  <%= link_to user_posts_path(@user) do %>
    <button type="button" class="posts-btn">See all Posts</button>
  <%end%>
  <%= link_to posts_new_path(@user) do %>
    <button type="button" class="add-post-btn">Create Post</button>
  <%end%>
</section>